version: '3.7'
services:
    node:
        image: smart_auth-node:latest
        volumes:
          - "./smart_auth/:/var/www/html"
        ports:
          - "8080:8080"
          - "3000:3000"
        links:
          - nginx
        environment:
          - JWT_SECRET=8TGUBVYI78T6FG897
          - DB_HOST=mysql
          - DB_USER=smart
          - DB_PASSWORD=doctrina
          - DB_NAME=smart_doctrina
          - TOKEN_SECRET=465RT7Y8UHJINBVRD45E6R7T
          - SMART_DOCTRINA_URL=http://nginx/
    mysql:
        image: mysql:latest
        ports: 
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=smart_doctrina
          - MYSQL_USER=smart
          - MYSQL_PASSWORD=doctrina
    api:
        image: smart_doctrina-phpfpm:latest
        environment:
          - DATABASE_URL=mysql://smart:doctrina@mysql:3306/smart_doctrina
          - CORS_ALLOW_ORIGIN=.
        ports:
          - "9000:9000"
        volumes:
          - "./smart_doctrina/:/var/www/html"
        links:
          - mysql
    nginx:
        image: smart_doctrina-nginx:latest
        restart: on-failure
        volumes:
          - './smart_doctrina/:/var/www/html'
          - './smart_doctrina/docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf'
        ports:
          - '80:80'
        links:
          - api
