version: '3.7'
services:
    mysql:
        image: mysql:latest
        ports: 
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=smart_doctrina
          - MYSQL_USER=smart
          - MYSQL_PASSWORD=doctrina
    api:
        image: smart_doctrina-phpfpm:latest
        environment:
          - DATABASE_URL=mysql://smart:doctrina@mysql:3306/smart_doctrina
          - CORS_ALLOW_ORIGIN=.
        ports:
          - "9000:9000"
        volumes:
          - "./:/var/www/html"
        links:
          - mysql
    nginx:
        image: smart_doctrina-nginx:latest
        restart: on-failure
        volumes:
          - './:/var/www/html'
          - './docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf'
        ports:
          - '80:80'
        links:
          - api
